---

jobs:
  include:
    - stage: Build

      language: minimal
      services:
        - docker
      script: docker build --build-arg CODECOV_TOKEN --build-arg "APP_VERSION=$(make version)" -t "${DOCKER_USER}/$(make name):$(make version)" .
      after_success:
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push "${DOCKER_USER}/$(make name):$(make version)"

    - stage: Publish

      language: minimal
      script:
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
        - scripts/docker_promote "${DOCKER_USER}/$(make name)" "$(make version)"
      after_success:
        - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/${TRAVIS_REPO_SLUG}

    - stage: Deploy

      language: minimal
      script:
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "deploy" "env_replace"
        - scripts/env_replace docker-compose.yml DOCKER_USER ENEDIS_EMAIL ENEDIS_PASSWORD SPURF_DATABASE_HOST SPURF_DATABASE_NAME SPURF_DATABASE_USER SPURF_DATABASE_PASS | sed "s|\\\$|\$\$|g" > docker-compose-env.yml
        - cat docker-compose.yml
        - cat docker-compose-env.yml
        - scripts/deploy "$(make name)" "@docker-compose-env.yml"

    - stage: Deploy

      language: minimal
      script:
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "deploy" "env_replace"
        - scripts/env_replace docker-compose.yml DOCKER_USER ENEDIS_EMAIL=ENEDIS_EMAIL_WILD ENEDIS_PASSWORD=ENEDIS_PASSWORD_WILD SPURF_DATABASE_HOST=SPURF_DATABASE_HOST_WILD SPURF_DATABASE_NAME=SPURF_DATABASE_NAME_WILD SPURF_DATABASE_USER=SPURF_DATABASE_USER_WILD SPURF_DATABASE_PASS=SPURF_DATABASE_PASS_WILD | sed "s|\\\$|\$\$|g" > docker-compose-env.yml
        - scripts/deploy "$(make name)_wild" "@docker-compose-env.yml"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Deploy
    if: branch = master && type = push

notifications:
  email: false
