---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spurf-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.19"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m

  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true

  values:
    nameOverride: spurf-db
    config:
      POSTGRES_USER: spurf
      POSTGRES_DB: spurf
    secrets:
      POSTGRES_PASSWORD: AgCHDrOwQD70BVK6dOz+l9TCd18T+LqB0hwT13RVuXf+AON7KH4dfgHqioidAvaaj26HTqkluAXeQHcLeR9ZdFXnqDmvIEF85S+yj6BJwmLquwy43Z7hYon/CUxpFVZMtIaarKpVsQfiNf3eaF6wGD2lQsxQbaRZUW4hAsUmjXJyNWTfvNx+zSEQHG/EPVlHwMFc9lz6Op1lCcGi50LAepFwQezatHm8WvaE663T4KkA/7MBfV1c/quR0LhuW9yWQOcdSaz3OX5DYkGeAQZgl2GM03C3U5nvxXgzHYcBM3U1CgOPTKi/EwxEVVKYZIWZTgHdvDoQDrJfhQmHnOa2BCGMpQi8fIHFj/GuJU/FJO011leMtiTPjv/XIQWRV3KjU+ox8lJpXEmUe9PbBdAr1b7KRcNCC3GpS/w8b0VnLdBMoRbALqOu9MVGv3xvM6iy1kxuW1vnWScbXwMe7mNFLrRtqff+IXEyh875CfYPqi05klAE/N5ddrwdTbq2O5OHWQj3iIDLiJ4hEcVzUuubrRoCz9SZOssdDnZ8eJQ74vtc5EL1S4PPiq1aD+UwRbggqWFATVUK+8a/xyfx0sqjcTIEEeIWna7hL3RHc35imqBjmOkIxBDVQbFLsGrpzFxhCId8cCsWemooT0XxNHlg3dckvelvHlzeuHzNTI6mFzRbn5i9OBwmnZ/E6Bj5g989RZ99EjgQTpOgrWPUKLdSRPmTYVOL65ZPngC6FBBBairjBPY9JYzenjqrFfZjYVimqEa6xfSGAmmB4bghGY0=
      FIBR_BACKUP_PASSWORD: AgBUbqVP+DQX7A4uiY3rAXqn6fzMBbE9p/SNheKA6wV/N6zRBGUnUUNz5/TbzCabMYgsWSc80Pdvzy2draL1+J8VguNlS3xdoLe0L2JGzPAzBr3qWC1RNY0+O6gkNbc/nlfp/QhkOORaGPWCbjECSY2bIvwGyAr15VbJWuP+2+KVxVtx/LIq17s1mRQFGItlbXeMj/Q0NXwdlbfV29H5SkeJxfYQnv0BcoLXLv2dPXFNUE5H4KeZEiMjQbCow/u3R16YbhafjtFOQ3mgFWsV4m1QarJt9duCtIEh0cEcDpCNBHP6PXKuAcsBpKV9GEEUc6XmOnE097cn9lCZsYY/drnKJfEqlA9/ARArTpISaaBoeU4mN8U9QRQiZhJOUQUwQBLYyDUJIzEhOs90ViErPyFZ5tmOO9NtLVPZFhyLM7nhNAc4M7PhCS728yi20slVooUC+KzSRLdwKsTrLcfKM1b9TdfPRrQC/5k80sw+jOq8LAnGYS0CNxK/r6ZODiHBlxv6ZE2/31xpqVIJOTjDH8rsY4kLB+4jy6KYFWSJOol/0RkPE2T5p9ot3BcRNGRmTTD2/9EROVTVZOI+Wg1hB+dfNiTONwdufi4Wpk4ZUTKSu8JGd4917lqzVZWFkvQ0QodxGl+plgkKIFN9HqrdIdoL5QO7HYWT9qKPyfh2riHrxipiKjqw+TQmrShLLntUtBrFb6SOyXvrr1ctwVpd7CkJccS7APo0UNcSHE4PBZl/Q7fs7z56RXgEktvXUdirN7QOytnn/wCErqSexsU=
