apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spurf
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.14"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: spurf
    schedule: "0 8 * * *"
    image:
      name: vibioh/spurf
      tag: "202103090939" # {"$imagepolicy": "default:flux-spurf-api:tag"}
    config:
      SPURF_LOGGER_JSON: "true"
      SPURF_ENEDIS_NAME: "sandbox"
      SPURF_DATAHUB_SANDBOX: "sandbox"
      SPURF_DB_HOST: spurf-db
      SPURF_DB_PORT: "80"
      SPURF_DB_NAME: spurf
      SPURF_DB_USER: spurf
    secrets:
      SPURF_DATAHUB_USAGE_POINT_ID: AgDfA+rfw7A+gAcvME+/lhsotLOQ/ALBeadoibCoNtO8WEKp+iSKK4TgU+x/gUrpFuCl2br/S7zGUZ2SwwbYKd3120lUjGeCr0dVnIHeXEor8BW1J5WgYO1AeMyuCGP9DdACQNKXzcshao2yUMLsCITgMUmJEHhFkvpnBZCAWeu3tW+fDV4tDhCG/p8EczZzsmBtHXnPDt8a0ledBPVDwofIMnzq9Lv7cx0+243P29iRoI5EmR2UKYoQAjEhCIt6mnkkMj0+K32YMBMu7nJtHA3BKF3UO/Zs/rN6+1f3WnBb/s5/TSyjgMkS0SrT/TvO1kkcmnk+Y8C0FC4KivBz8+2JHp3EynKjknnqC5T/xiK6JSo4r8JIT1cXLwxZCHEr6/LPyKajGbwv2SbvIF7q7BX7NWe+wsgdJ4DmGytX4t7Li1dntUZV0WxaCAIRP3B+4MEZ78CIn3SOyxcEKZkty1hRHqnEVURZAmlbd7RNFSyhjOQfa95QMsJQXHb2qmgGBNo8zGsUaY6tAy91uQcpCaL/VgU3wi3pT0Fl3Pj7152KY3XB2hIwUza9EFFx0V0uQaKzYAB3huS/mON6dEmH3YX6P5pk1nSnFnKRncP0pc12o92Qppz7ZWyRsAXyooeQc31QcJMDnibxYj/fnyt2v1zT7b+uF2y5Qb13oSpYu4F5ED3EIOWeA3YfcnYQ7JRq1Nj5O1zR+x7RyhlNRRmAyA==
      SPURF_DATAHUB_CLIENT_ID: AgBYntB5Z8SP2oh4qHKzKkkwE/4CZTgJgY/+4blnMuozNN7C2wXCIY//BoF32LAK2I2wkZOZHuBzIpPYtv4lpMmOX4mjpcuydq9sxazJaB0I8aagwsOc+7gKBDYU0pKeq/GC+Eitp8Raw527KngBIUAffhTGjbJE6Nbw/dWdSKQtFZRyMTFa1nEkc2wNyD2JEfmfIIoBqszmpb7pUAdTuAOLIF0+W7B/Ycxc815tKN/NQjg96eKTjLt0ckSW6sDKLcnPyvdlcMmvoQowufhTphL97rVcrVSp9l8ErJ7xarKFBpN02ahLxt+il3IIkv/1kAcZpYSz37Vi4FVAYfPjjIsrjPM7YIUNT6p3dA7/aLkAs3XFw2UXmid1MpG5ayoLLbnOgCqImjrOdwZ3GHgVWufIs4CVjo6jD8PZgVMDr6mD2WB2uXd+K0nzzmKHyQ8FXMyLldsrsgR2Yxq0/1FFrsihuybclTj8H3yvHgNYc18ttIXepI3E8GkbxFN8MSf/nRQpx7RdJtLUpAn5iVPje6QnOjsJ2gogubfIE8quAfCA7tHCl4dOikpqX7YI835+mq12DTqapav70PwX3bn2CM515Xh+mnsdfo5CeZrRQSCi9PR0swtkrTY8McsS+MPnx8xZKw55YcyTrVJvA6+EZ1bnWp9ogzdeaTZFdxqsdaceoKPpTDcSeFF7/36R8UDT73pVo4M4Ksz94SpdAC09GIARUWxGwQplZnk9E1Ro/X7K6PElj5M=
      SPURF_DATAHUB_CLIENT_SECRET: AgCALD4iFRPsbo79SGQe1Nuw421ezWM0ujzMI2+bpu7xe/BMnq6J3uO4gO8i+9kuigf36yVuP5bJaGCbeKIJc1HZJI8bz4iv0FDBCp5fipqjEbc4aEb9PCEN54cD6rHzfD+CaOtFMRi2/WVDr+uP7J+haQrluab3PcbrB6JY507m3wVnMb3GCfJl+I3V4QteJEUixeRNwtR5sfgFT8kUFfO3pLuvFo4knM49tqr3PwN0A+2+ccuZVf6/4QWotxL2w8uEz312cE1TYgV6RiTxsVR9XweugTmLteWVXZDI6lQxtZgzvRUAmizonlqQov8y5nUSFODOVrmJ7rLotMIUBYyamazEPCmjzZyDCgyVEfsA19jyBnOAvosMxAcDXXFLq9p4A/os8AsslTpE1PkslAhMcqnR5v7a/E0Za9yDuTpa0HZtLL69gWfB8AaswdTQgMbmtQeppJJE1YSxgbmkSetCgHaALVvoGvqI/F5R31+/syjUcP5BFKG6W15O4KBcOkx098T8u8Rs0tyBhhTqSwYZ1eU9HQRJCESnVOI3j2zrm1KxPAiGr84JvORsJS0+Wheaby4d45YnJMBbS8nMZrbBFU4QVvMpG8GkpTNXig1pfqjp8C0Cluzl0EsC7hAjILss1vHk0xhWVwRN2O3Q8xkF3TcVUwOE8ZbLlbbARSKHbUklpp83Ir85gM6XgPd+OkjCnuAiutLk0Xdyl2FgKS/pwD6BjiNfTxHd+AVIXyPkSKEQt7Y=
      SPURF_DATAHUB_ACCESS_TOKEN: AgB5BOx/gdvLr+gJxXBEBOlgxoarMzYG1fFlGuR+8I2yjZ4N+FUmw2YG1g+EXDqAxYTFtdYYD7vAT7YGtZEzhGnEKox5GT9hEh69Kzt1TqXH8DgGriAZCVdPa6oB67IkpvnG5LeOatST70f38ruKJeSzsR7h3c0aFaeK7eemFH7uOTSvg7yaHh3tZEN9Iao8imBhxG2aJ5ubkDfJ5dWwQl2PehVe4sQeUiG6uutMo6KCygjWFTOEV117MoDPfXUNFrT+opu0VccNgvqy+JSfNnzYEYNICESQvPKPvX9xowh2jWm9TVKIEFV1q6+cpdAG86xeq3iFCleUAi5aBcPF+31q+t6W6pVtbauQe0/f3GjQlPVH8hGdFM7sYUMiouoQ4jrYRqN09FvtoGDftHqOjfJzqYr4TysGX6AJsAXcmZpXX5ZDGyFkRnyFfhziW24mhLCPEblDmNn52gxoP//dychZR7nGcaPRIPjRXR/Ug8+hnKmYE94kIq9j+kgnvWsbt7BQshwdxkXkonNKaxpt+GQKeIYHfiytCqtAb0PEGvOqvoU2EqZFF2pjM/UEy2rKBopui+HLwIb2CRGyGW1UvTg4brgqbYM5kAFr5Q+gH4g2v0eDnNd0DlfEO7aFi+ZgFdSe53my/iSDBdFnEUt+X70eGX/qXd8w5XYYBHJ0IAFcNjHsNHwjLZbZzpv/jX11b4uWbq6EgrYkeycfY+sOF6nN/U+EFl5gqydhUPvC+hb1k2cPREpUTuh8jvHZ29MJ2to/DWEhEhQ=
      SPURF_DATAHUB_REFRESH_TOKEN: AgAoDTK9yU+lWYBlVjTKh1rxJ9LFkCFZJfya3Ltl6xpBlR1lEuaDzi/Mda6/7XIy7y1rpfrmjebqeOv9z+kAu8IOYyjc/RjBYnIx9R+xDx18qa3ecUyd5OKh97wx2oHTmhbluD+rqrP3OYtnMOSaxTmJ1Lj7Hj/32UMTfemKc0ggtlDX8o2ZB1WwH54t7wU/fi+tXPJkqaEMQSCNV45XyCaUN3caFCW9eFscfeNreyS6v14e1rJbFRO1dmLvCTcHLd30x7rK97ZN9PwJSvD18BPl62mrunA62m00/Zp8FPQx6XHk6gAac0auGgWTK4U94jbtSiY8qTklp4LxCOF3vwxyzFBiJq+Z6THsuL+Eiq9Vp5lnUseL7AQYgcc0ko9X+XeIODlxrLFl1HsDmfDqOYeAGdyuUFg1kdmpSrHWwpJ1EpPDcKq0FntPwgqTfUx59mSKBwZtTJQuIo0k0pe5C7Mw4XVCgFY/zSBVRt/S7yktwzxS4U6T8CtZ3zxim/BnXjV07ifmCk44wW8sbMgzyMNkhQj5YKTrIAD+CJWp5OJZgE1ABk/BeaqLJMdOEcKMtpkqB2AZyFe7ucVMtLYnrDTHlBjE0Lf1YjmlQCDGttTpHBQcgNuYe9SscxspuBvSr+zQJcrWqEI43GqB+eyCaMw9uWmzE6im4UPKyLmcSEMiHe6vyHMZo6ik3dt6ofnoliHyg1Xpo/fdYKYeX+aR2t1FFnMEWQQicGtzjtorB+d9jl7H9fZGOheOkFpEs7MG
      SPURF_DB_PASS: AgCd2ffLCbeR7gbe+wL5/NvcJ/MENHndRvPj7Akw3SJItETHxTDh2zSeH6rahuAlynLRYtxDAOAYy+Drxmp0gdwMFhlA5sdC5DAe2bgNAjON13gq7QcZGaL3yhuInVwGJyI5qFdFYO6JZJ4POV9XhXx7sbhfSTOrD2F4EDpoDEfupePeb1BSr3izT4lc1tptNdxPeyqJ60/XcZyx2WLzPeLWLkmsEXQMABi8kCSnGowcLLGmnas8iAGAqqUc5f3n2r2JhfNu4/o824hff65jbmFWxmU+OcWvPgQCZnvc8LjBqH4JGiuVFIaT93jcbihZv8cPMxMqdmoib72VlgdwHgBTyaW4danc14nlfDQD2EcFRzhaAW3h4SPWV+EYlrIIRyauV+xdpVPENlZ8ry6jUntXdPSyDeEoYC1vysXtT49d6Op0kJkO7ZTySxoY1HsGcfJzC+YkzTTYV4UzsPQIaOVtrvoPoOJn9HTwnpqRh9t5JfVlth6ReVFwpoIDvArcr5MUYCV3s2JEcFq3oaHwILJS+x3V0x8VvPlgNDI9bFEFSUJPk1zVnibp6gD0M+psdulsOi7mYWXG6woLVRj+Y6BJueAFCyG+uHgc2ZBu7v9yB6WSzHWxpUZNLRu2DAQeN5+VQoFzg3U5J257z7mQ4uxBvC3MimLt+bDnP79FzTBj7eJAhSK2mNJ5V+4/wALrhkeVJM5nC9kAytANuFbLSc9LfaHTZhi7fsvklCHkTKblmWozt2QoVqPw9qgRfi5XMounlryPvkJR0oRSGr8=
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spurf-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.19"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: spurf-db
    config:
      POSTGRES_USER: spurf
      POSTGRES_DB: spurf
    secrets:
      POSTGRES_PASSWORD: AgCHDrOwQD70BVK6dOz+l9TCd18T+LqB0hwT13RVuXf+AON7KH4dfgHqioidAvaaj26HTqkluAXeQHcLeR9ZdFXnqDmvIEF85S+yj6BJwmLquwy43Z7hYon/CUxpFVZMtIaarKpVsQfiNf3eaF6wGD2lQsxQbaRZUW4hAsUmjXJyNWTfvNx+zSEQHG/EPVlHwMFc9lz6Op1lCcGi50LAepFwQezatHm8WvaE663T4KkA/7MBfV1c/quR0LhuW9yWQOcdSaz3OX5DYkGeAQZgl2GM03C3U5nvxXgzHYcBM3U1CgOPTKi/EwxEVVKYZIWZTgHdvDoQDrJfhQmHnOa2BCGMpQi8fIHFj/GuJU/FJO011leMtiTPjv/XIQWRV3KjU+ox8lJpXEmUe9PbBdAr1b7KRcNCC3GpS/w8b0VnLdBMoRbALqOu9MVGv3xvM6iy1kxuW1vnWScbXwMe7mNFLrRtqff+IXEyh875CfYPqi05klAE/N5ddrwdTbq2O5OHWQj3iIDLiJ4hEcVzUuubrRoCz9SZOssdDnZ8eJQ74vtc5EL1S4PPiq1aD+UwRbggqWFATVUK+8a/xyfx0sqjcTIEEeIWna7hL3RHc35imqBjmOkIxBDVQbFLsGrpzFxhCId8cCsWemooT0XxNHlg3dckvelvHlzeuHzNTI6mFzRbn5i9OBwmnZ/E6Bj5g989RZ99EjgQTpOgrWPUKLdSRPmTYVOL65ZPngC6FBBBairjBPY9JYzenjqrFfZjYVimqEa6xfSGAmmB4bghGY0=
      FIBR_BACKUP_PASSWORD: AgBUbqVP+DQX7A4uiY3rAXqn6fzMBbE9p/SNheKA6wV/N6zRBGUnUUNz5/TbzCabMYgsWSc80Pdvzy2draL1+J8VguNlS3xdoLe0L2JGzPAzBr3qWC1RNY0+O6gkNbc/nlfp/QhkOORaGPWCbjECSY2bIvwGyAr15VbJWuP+2+KVxVtx/LIq17s1mRQFGItlbXeMj/Q0NXwdlbfV29H5SkeJxfYQnv0BcoLXLv2dPXFNUE5H4KeZEiMjQbCow/u3R16YbhafjtFOQ3mgFWsV4m1QarJt9duCtIEh0cEcDpCNBHP6PXKuAcsBpKV9GEEUc6XmOnE097cn9lCZsYY/drnKJfEqlA9/ARArTpISaaBoeU4mN8U9QRQiZhJOUQUwQBLYyDUJIzEhOs90ViErPyFZ5tmOO9NtLVPZFhyLM7nhNAc4M7PhCS728yi20slVooUC+KzSRLdwKsTrLcfKM1b9TdfPRrQC/5k80sw+jOq8LAnGYS0CNxK/r6ZODiHBlxv6ZE2/31xpqVIJOTjDH8rsY4kLB+4jy6KYFWSJOol/0RkPE2T5p9ot3BcRNGRmTTD2/9EROVTVZOI+Wg1hB+dfNiTONwdufi4Wpk4ZUTKSu8JGd4917lqzVZWFkvQ0QodxGl+plgkKIFN9HqrdIdoL5QO7HYWT9qKPyfh2riHrxipiKjqw+TQmrShLLntUtBrFb6SOyXvrr1ctwVpd7CkJccS7APo0UNcSHE4PBZl/Q7fs7z56RXgEktvXUdirN7QOytnn/wCErqSexsU=
