---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spurf-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.32"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m

  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true

  values:
    nameOverride: spurf-db
    config:
      POSTGRES_USER: spurf
      POSTGRES_DB: spurf
    secrets:
      POSTGRES_PASSWORD: AgBOq6KzHzS/oORuR4oqea5tdTkCszXlljb+y5+rL6Uni1t1yl3yiK9O/S0rgUwhnjWhjwS7gjbE1djrlOrhNs2GAOlKZbsilzkK+w1UaHqRhrWk8L0unOFxYiXl9G1/LoEy7+KIcwm8FwTMBkdk35Zc5Z0pCCzdgPOQBwL0b51Xa+0G0kbc0bYBwZ5CynjhyoTg5GGRYEyMaTbe7qwZZWPb1H+UkYzTChXv+Nfup3TCLG9kZ5klaxF6TXrcGXCoHpaZgPqmcNWvBASwbZajV1y8N04bLmk2ulCBvsWCIM5YIGfWlJBIwkdwe2pQRv2Makq4JhYnByxbzkZCJs8oMIEIZ2LcIHX6P4a8tQ6lElL4zeS/YK/57MxgPWGaa48ngFQOSpxPfhc4QYWi2kVW6Z+m4RcA3IyBi4KoYqwPxQjLVoDd5bgILK2SzDzMhYCfBVj9SUsnJuYWVFF4a0ij8Y/hCvqdoeexUDieFY2/Alaf8hjkzRmP4TN+8UdEzVcYRZRFwVIVBDkEk8a8xSufhoLh7Pm0pLhLQJnr+3LVANYoDo3SJX5Unli9J+6pRhLrbr1JUO3f203/LYtlLFjxKWbqW3O3oVkN9r9ygdlOuJumNoI8gECP05GiPF3RdipEHCfDMPCDCtyUQkltOJLJOpZ8TlYoG+2hkfw6kxlWToR4n5U5pOG4PD2nFNUGcr91yTe8zTmQGD6vdC1SotpGLawRmVLompQSjsa+mHP0piXWYj0tu3w9yLGuzb2g8tycJFTB4seStSiz3cSZ0WA=
      FIBR_BACKUP_URL: AgC5X8o4AbqeLWhHm8FKq0XqtmUUiiifpW1o3Z1bFh/ctr6f58rZ6eHJkpLeLlXKkLbbfWpYgyjWMN2LKGGPo2Dpg6WVCe8EQdHd4YyaIBhtNh/SZCmG+NaqgPGDrmlrQFmyu92Pu/eh5CU8xDyJM+arqvckUJ8QJT7yFqiAudxiu0653ZZ5M+YeGwdJuL29xM9xzQQsH5Mmgjv2ZoLJ8Gd6c6hg+5Jgs1yXqefHscn2HCsYj94ocUOtspLCfS5Ec5ANej4JEnIZdFWhBp2PUeDa1h+i5OErW/xm1yIq9AokYBDreoy60m+HWWQpLt6JTxr6ttcxsWuj9yPCIE5DoEU9P5/sFTByrpIkZAAVEcmnxYXwBIm1W0BI7iwsFVH1+wHb9+2THcaTwMQjzwG0XY5/adtYbmT/tDoYzExQOduztLmTpuHOX8gw4XKIXGYIq5aKSc1y5hF/cSni0CWUmhF5C8rP5rS0G0i3zGWuo3rt6OB3uBr99gzhUm+4OQXoxKdgmdkyRnIC5CcqzBVC/LIZg0f5s0XiSyOd5lJUI74MnflSCY4NZnCoZFQpR0+5kh3+R33xuKwMSov1J5TGkIymYEFOOqY3uVVR7+SgkbKErMedW6Wtq8fc8EK/rglCHQMH3r7k1oxnTMp/D6G63aF/C7GG1AVDoT8OSKEEyEes+LcvteP/jP7IGQ8te7QARwBRBjLa/kNm4utPxYfWrDnMGkevbDsHGkP4TNCYR/QaSA==
      FIBR_BACKUP_PASSWORD: AgBAUsNpQX3pPbsm9HmzSetUSmeh3CKx7pxDaOqXkwvtKazYBUtGU/fRqibid99gERoA48Agk6w9Jp9fC3n+Ixv1AT+mvDcW9eaNnpsKsyD94/xVOZpDvZBQdvmJSgG3MelzJUyFBzGEOab+09/36I76M0lYomqJZtGub6IIWYM/eMjWqB8Oi9VAMeHnv83NfuaEKdZcM5YSDhfrYyB5QhWsk0jZWy0Nj0FRjMUHEkPcGJ9G0SGBAOicJ9burgvS/I+KO/Jpr2PiFa6zUWagBAXT/vE3qV1JR7QOo1FlbFTW7pBA0xH1N5VdQyUSQ/Y8eDOk4OqtPazmHTcF1duwL8/3J0PXOdVurIRTkDCqglbT4xIgttyVJddMwDByCxhod8J593K8ApLDc8seH1uJtIIaSjfWIdeoz7AD1cUGs3kFtizDtlSzZHs3AnhVlU0osniun6SY3MUcMz11M3GU9TM+ZJo8TRWxgBde8752D93ckUcvkEAcH58gcpvK0vbISQhvUWEbrk2NSUy0HFa5QdmS8SMCDdlpvH5OmGT6rom4ojF9pxl3x3jA1fSS1o1wO0DwHvI2UTaKKeCNZs6UKqXMoOMLxXy2vKSO5G3h+bN4L98PYJTeaFks93ARcJlY8L+ZOx4izanT6WUSaHFnqhW32sT/ksM6frkPxlhhSnuvKLl1dxzgG3jGNRRUDdrt0fPHexIGd/SPWLWS4bEd+Ds+NM8ugwUwb2Xp+roRaKM08FvOW0f7QkTRLIusfVMXgM5XjaZk8LtTiFrlM5M=
